---

name: Examples

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.26'
          check-latest: true
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go mod tidy
      - name: Run read table example
        run: cd examples && make read
      - name: Run write table example
        run: cd examples && make write
      - name: Run create table example
        run: cd examples && make create
      - name: Run open table custom
        run: cd examples && make custom
      - name: Run search table example
        run: cd examples && make search
      - name: Run database export example
        run: cd examples && make export
      - name: Run database documentation example
        run: cd examples && make documentation
      - name: Run database schema example
        run: cd examples && make schema

      - name: Run bytes example
        run: cd examples && make bytes
      
      - name: Run reader example
        run: cd examples && make reader